---

- name: Install SSMTP (apt)
  apt: name=ssmtp state=installed update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install SSMTP (yum)
  yum: name=ssmtp state=installed
  when: ansible_os_family == 'RedHat'

- name: Set up ssmtp.conf
  template: src=ssmtp_conf.j2 dest=/etc/ssmtp/ssmtp.conf
